version: "3"
services:
  nginx-react:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    networks:
      - jj-net

networks:
  jj-net:
    driver: bridge